//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch_Box
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int paymentID { get; set; }
        public string nameOnCard { get; set; }
        public string cardType { get; set; }
        public Nullable<long> cardNumber { get; set; }
        public Nullable<int> orderID { get; set; }
        public string expiryDate { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<int> discountID { get; set; }
        public Nullable<double> totalPrice { get; set; }
    
        public virtual discount discount { get; set; }
        public virtual order order { get; set; }
    }
}
